# Generated by Django 5.1.7 on 2025-03-26 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designedprompt',
            options={'verbose_name': 'プロンプトテンプレート', 'verbose_name_plural': 'プロンプトテンプレート'},
        ),
        migrations.AlterField(
            model_name='designedprompt',
            name='input_keys',
            field=models.JSONField(verbose_name='キー名 (["name", "age"])'),
        ),
        migrations.CreateModel(
            name='GenerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_object', models.JSONField()),
                ('generated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.designedprompt')),
            ],
            options={
                'verbose_name': '生成履歴',
                'verbose_name_plural': '生成履歴',
            },
        ),
    ]
