# Generated by Django 5.1.7 on 2025-03-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_designedprompt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationhistory',
            name='style',
            field=models.CharField(default='default', max_length=16),
        ),
    ]
